apiVersion: v2
name: pagopa-print-payment-notice-generator
description: Microservice that handles services for notice print generation
type: application
version: 0.6.0
appVersion: 0.0.5
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
